### ISSUE TITLE
Mise en place de Django REST Framework pour l'API

### ISSUE THREAD

**Issue by hippync** [hippync/fitness-app#4]
### Description
Configurer Django REST Framework pour exposer une API pour le projet.

### Subtasks
- [x] Installer Django REST Framework
- [x] Créer des serializers pour les modèles
- [x] Créer des vues APIView ou ViewSet
- [x] Configurer les routes de l'API

### Dependencies
- Modèles Django

### Notes
Référez-vous à la documentation de Django REST Framework pour les meilleures pratiques et exemples.
