### ISSUE TITLE
Configuration de React et Redux, création des composants de base

### ISSUE THREAD

**Issue by hippync** [hippync/fitness-app#5]
### Description
Configurer l'environnement de développement pour React et Redux, et créer les composants de base.

### Subtasks
- [ ] Installer React et Redux
- [ ] Configurer le store Redux
- [ ] Créer les composants de base (e.g., Header, Footer, etc.)

### Dependencies
- Configuration de l'environnement frontend

### Notes
Utilisez Create React App pour initialiser le projet React.
