### ISSUE TITLE
Mise en place des tests unitaires pour les composants React avec Jest et React Testing Library

### ISSUE THREAD

**Issue by hippync** [hippync/fitness-app#6]
### Description
Écrire des tests unitaires pour les composants React en utilisant Jest et React Testing Library.

### Subtasks
- [ ] Installer Jest et React Testing Library
- [ ] Écrire des tests unitaires pour les composants de base
- [ ] Exécuter et vérifier les tests

### Dependencies
- Composants de base React

### Notes
Consultez la documentation de Jest et React Testing Library pour des exemples de tests.
